### ISSUE TITLE
Why check the drawFlag?

### ISSUE THREAD

**Issue by johanlindfors** [Tandolf/chip8-emulator#21]
https://github.com/Tandolf/chip8-emulator/blob/207f2ceb03e0986083df7fe4a94a06ceaa963b0d/src/test/java/se/andolf/emulatorTest.java#L50

I don't understand why the drawFlag = true indicates a success of this test. The instruction 0x2NNN shouldn't force a draw, should it?

I suggest checking the PC against the "address" of subroutine.

**Comment by johanlindfors** [comment]
assertTrue(514, cpu.getPC());

**Comment by Toerktumlare** [comment]
fixed by pr #24
